### ISSUE TITLE
Conformance tests not executable on command line

### ISSUE THREAD

**Issue by patrickwestphal** [SANSA-Stack/SANSA-Inference#2]
When calling `mvn clean test` e.g. in `sansa-inference-spark/` I get
```
net.sansa_stack.inference.spark.conformance.RDFSConformanceTest *** ABORTED ***
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: net.sansa_stack.inference.spark.conformance.RDFSConformanceTest
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  ...
  Cause: java.lang.NullPointerException:
  at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:190)
  at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:186)
  at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
  at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
  at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
  at net.sansa_stack.test.conformance.TestCases$.loadTestCases(TestCases.scala:29)
  at net.sansa_stack.test.conformance.ConformanceTestBase.<init>(ConformanceTestBase.scala:38)
  at net.sansa_stack.test.conformance.RDFSConformanceTestBase.<init>(RDFSConformanceTestBase.scala:17)
  at net.sansa_stack.inference.spark.conformance.RDFSConformanceTest.<init>(RDFSConformanceTest.scala:21)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```
for `RDFSConformanceTest` and `OWLHorstConformanceTest`. Seems, the problem is, that in `net.sansa_stack.test.conformance.TestCases` (part of sansa-inference-tests) the `directory: File` variable passed in, holds e.g. the path `file:/home/me/.m2/repository/net/sansa-stack/sansa-inference-tests_2.11/0.3.0-SNAPSHOT/sansa-inference-tests_2.11-0.3.0-SNAPSHOT-tests.jar!/data/conformance/owl2rl` and `directory.listFiles()` returns `null`.

**Comment by LorenzBuehmann** [comment]
The problem is that with `mvn install` it seems that the Jar file to `sansa-inference-tests` is kept while with `mvn test` it is extracted. That means, working on the Jar file fails because the Java `File` object isn't designed for Jar containers.
